


development:
  adapter: postgresql
  encoding: unicode
  database: hoardle_dev
  pool: 5
  username: hoardle
  password: hoardle
  host: localhost


test: &test
  adapter: postgresql
  encoding: unicode
  database: hoardle_test
  pool: 5
  username: hoardle
  password: hoardle
  host: localhost
  

cucumber:
  <<: *test
  